spring:
  application:
    name: devops-main
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # Hibernate DDL (none, validate, update, create-drop)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

user:
  profile:
    url: ${PROFILE_URL}

springdoc:
  api-docs:
    path: ${MAIN_SWAGGER_PATH}
  swagger-ui:
    path: ${MAIN_SWAGGER_PATH}

urls:
  domain_server: ${DOMAIN_URL}
  api_gateway_server: ${API_GATEWAY_URL}