spring:
  application:
    name: devops-main
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        sslrootcert: ${SERVER_CA_CERT}
  jpa:
    hibernate:
      ddl-auto: none # Hibernate DDL (none, validate, update, create-drop)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

user:
  profile:
    url: ${PROFILE_URL}

urls:
  domain_server: ${DOMAIN_URL}
  api_gateway_server: ${API_GATEWAY_URL}
  api_gateway_server2: ${API_GATEWAY_URL2}
  api_gateway_server3: ${API_GATEWAY_URL3}
  api_gateway_server4: ${API_GATEWAY_URL4}
  api_gateway_server5: ${API_GATEWAY_URL5}
  api_gateway_server6: ${API_GATEWAY_URL6}
  api_gateway_server7: ${API_GATEWAY_URL7}
  api_gateway_server8: ${API_GATEWAY_URL8}