spring:
  application:
    name: devops-main
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        sslrootcert: ${SERVER_CA_CERT}
  jpa:
    hibernate:
      ddl-auto: none # Hibernate DDL (none, validate, update, create-drop)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

openapi:
  service:
    url: ${API_GATEWAY_URL}

user:
  profile:
    url: ${PROFILE_URL}